export interface regionFormat {
  "name": string,
  "topLevelDomain": string[],
  "alpha2Code": string,
  "alpha3Code": string,
  "callingCodes": string[],
  "capital": string,
  "altSpellings": string[],
  "region": string,
  "subregion": string,
  "population": number,
  "latlng": number[],
  "demonym": string,
  "area": number,
  "gini": string,
  "timezones": string[],
  "borders": string[],
  "nativeName": string,
  "numericCode": string,
  "currencies":{
    "code": string,
     "name": string,
    "symbol": string
  },
  "languages": any,
  "translations": any,
  "flag": string,
  "regionalBlocs": any,
  "cioc": string
}